//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI.Database.Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class cond_archive
    {
        public int dataID { get; set; }
        public Nullable<int> cond { get; set; }
        public Nullable<int> temp { get; set; }
        public string measurment_date { get; set; }
        public Nullable<int> sourceID { get; set; }
    }
}
