//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI.Database.Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_water
    {
        public long customer_customerID { get; set; }
        public int first_sourceID { get; set; }
        public int second_sourceID { get; set; }
        public Nullable<int> firstSourcePercentage { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual source source { get; set; }
        public virtual source source1 { get; set; }
    }
}
