//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI_DataBase_Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customer_water = new HashSet<customer_water>();
        }
    
        public long customerID { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string plant { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<decimal> acid_price { get; set; }
        public Nullable<decimal> caustic_price { get; set; }
        public Nullable<int> demand { get; set; }
        public Nullable<long> num_trains { get; set; }
        public string date_added { get; set; }
        public string notes { get; set; }
    
        public virtual ICollection<customer_water> customer_water { get; set; }
    }
}
