//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI_DataBase_Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class resin_products
    {
        public resin_products()
        {
            this.vessels = new HashSet<vessel>();
        }
    
        public int resin_product_id { get; set; }
        public string manufacturer { get; set; }
        public string name { get; set; }
        public string model_number { get; set; }
        public string resin_type { get; set; }
        public string primary_type { get; set; }
        public string group { get; set; }
        public string teir { get; set; }
        public string chemical_structure { get; set; }
        public string physical_structure { get; set; }
        public string color { get; set; }
        public string total_capacity { get; set; }
        public string salt_split_CAP { get; set; }
        public string price_per_cuft { get; set; }
        public string comments { get; set; }
    
        public virtual ICollection<vessel> vessels { get; set; }
    }
}
