//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI_DataBase_Updater
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rtitestEntities : DbContext
    {
        public rtitestEntities()
            : base("name=rtitestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cond_archive> cond_archive { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_water> customer_water { get; set; }
        public virtual DbSet<resin_products> resin_products { get; set; }
        public virtual DbSet<source> sources { get; set; }
        public virtual DbSet<train> trains { get; set; }
        public virtual DbSet<vessel> vessels { get; set; }
        public virtual DbSet<vessel_historical> vessel_historical { get; set; }
        public virtual DbSet<water_data> water_data { get; set; }
    }
}
