//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI.Database.Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public source()
        {
            this.customer_water = new HashSet<customer_water>();
            this.customer_water1 = new HashSet<customer_water>();
        }
    
        public int sources_sourceID { get; set; }
        public string river { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string measurement_location { get; set; }
        public string exact_lat { get; set; }
        public string exact_lng { get; set; }
        public string street_number { get; set; }
        public string street_name { get; set; }
        public string street_lat { get; set; }
        public string street_lng { get; set; }
        public string feature_class { get; set; }
        public string miles_from_site { get; set; }
        public string post_code { get; set; }
        public string place_name { get; set; }
        public string county_number { get; set; }
        public string county_name { get; set; }
        public string state_name { get; set; }
        public string agency { get; set; }
        public string agency_id { get; set; }
        public string full_site_name { get; set; }
        public string unique_site_name { get; set; }
    
        public virtual ICollection<customer_water> customer_water { get; set; }
        public virtual ICollection<customer_water> customer_water1 { get; set; }
    }
}
