//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI.Database.Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class train
    {
        public int trainID { get; set; }
        public string name { get; set; }
        public Nullable<int> number { get; set; }
        public string gpm { get; set; }
        public Nullable<int> num_beds_cation { get; set; }
        public Nullable<int> num_beds_anion { get; set; }
        public string using_manifold { get; set; }
        public string regens_per_month { get; set; }
        public string regen_duration { get; set; }
        public string has_mixed_bed { get; set; }
        public string has_historical_data { get; set; }
        public int customer_customerID { get; set; }
    }
}
