//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI_DataBase_Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vessel
    {
        public int vesselID { get; set; }
        public Nullable<int> vessel_number { get; set; }
        public string name { get; set; }
        public string size { get; set; }
        public string bed_number { get; set; }
        public string lbs_chemical { get; set; }
        public string date_replaced { get; set; }
        public string replacement_plan { get; set; }
        public string throughput { get; set; }
        public string num_regens { get; set; }
        public string toc { get; set; }
        public string with_degassifier { get; set; }
        public string with_polisher { get; set; }
        public string vessel_customerID { get; set; }
        public int train_trainID { get; set; }
        public int resin_data_product_id { get; set; }
        public Nullable<double> Salt_Split { get; set; }
        public Nullable<double> price_cuft_resin { get; set; }
    
        public virtual resin_products resin_products { get; set; }
    }
}
