//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTI_DataBase_Updater
{
    using System;
    using System.Collections.Generic;
    
    public partial class vessel_historical
    {
        public int sampleID { get; set; }
        public string date { get; set; }
        public Nullable<int> lbs_chemical { get; set; }
        public string throughput { get; set; }
        public string num_regens { get; set; }
        public string toc { get; set; }
        public string vessel_historical_customerID { get; set; }
    }
}
